languageCode = 'pl'
title = 'sdokFILM'
theme = "nightfall"

[params]
user = 'ksmvsky'
hostname = "sdok.pl"
footerHtml = 'Instagram - FilmPolski - FaceBook'
readingTime = false
color = "orange"
ico = "/assets/ico/Yakto_icon_universal.png"
bckg = "/assets/vid/bckg.mp4"

[params.author]
name = "Szymon Kosmowski"
url = "/about"

[[params.social]]
name = "Advertisments"
url = "/categories/advertisement"

[[params.social]]
name = "Films"
url = "/categories/film"

[[params.social]]
name = "Music"
url = "/categories/music"

[[params.social]]
name = "Selfmade"
url = "/categories/selfmade"

[[params.social]]
name = "Reels"
url = "/categories/reel/"

[[params.social]]
name = "Videoclips"
url = "/categories/videoclip"


[menu]

[[menu.header]]
name = "about"
weight = 1
url = "/about"

[[menu.header]]
name = "new"
weight = 2
url = "/posts"

[[menu.header]]
name = "tags"
weight = 3
url = "/tags/"

[[menu.header]]
name = "hire"
weight = 4
url = "/hire"
