languageCode = 'pl'
title = 'YaktoMedia'
theme = "nightfall"

[params]
user = 'ksmvsky'
hostname = "yakto.media"
footerHtml = ''
readingTime = false
color = "orange"
ico = "/assets/ico/Yakto_icon_universal.png"
bckg = "/assets/vid/bckg.mp4"

[params.author]
name = "yakto.media"
url = "/about"

[[params.social]]
name = "Reklamy"
url = "/categories/advertisement"

[[params.social]]
name = "Filmy"
url = "/categories/film"

[[params.social]]
name = "Muzyka"
url = "/categories/music"

[[params.social]]
name = "Selfmade"
url = "/categories/selfmade"

[[params.social]]
name = "Rolki"
url = "/categories/reel/"

[[params.social]]
name = "Teledyski"
url = "/categories/videoclip"


[menu]

[[menu.header]]
name = "o mnie"
weight = 1
url = "/about"

[[menu.header]]
name = "nowe"
weight = 2
url = "/posts"

[[menu.header]]
name = "kategorie"
weight = 3
url = "/tags/"

[[menu.header]]
name = "kontakt"
weight = 4
url = "/hire"
